### ISSUE TITLE
Is it necessary to unload SAORI when unloading SHIORI?

### ISSUE THREAD

**Issue by nikolat** [ponapalt/yaya-dic#11]
```
SHIORI3EV.OnUpdateReady : void
{
	// OnUpdateReadyならロード中のSAORIをすべてunloadする
	SHIORI3FW.SaoriUnloadAll
}
```
In the OnUpdateReady event, SAORI is unloaded.
When SHIORI is unloaded, should SAORI also be unloaded in this way?
```
unload
{
	//...
	SHIORI3FW.SaoriUnloadAll
	//...
}
```

**Comment by steve02081504** [comment]
@nikolat I've just looked at the yaya code and it looks like after the unload call yaya automatically unloads the libs.
https://github.com/ponapalt/yaya-shiori/blob/500/basis.cpp#L264L265
I'm not sure if lib loads are logged at the dic level, if they are I think it need to be corrected to none lib.
If not, please leave a comment in the unload function in case someone has the same question in the future
