### ISSUE TITLE
Why is SHIORI3FW.AUTO_DATA_CONVERT enabled by default?

### ISSUE THREAD

**Issue by nikolat** [ponapalt/yaya-dic#9]
I believe that there are now more new YAYA users than users migrating from AYA5 to YAYA.
Isn't it more harmful to have SHIORI3FW.AUTO_DATA_CONVERT enabled by default?
`#globaldefine SHIORI3FW.AUTO_DATA_CONVERT 1`

**Comment by nikolat** [comment]
（ゴリ押ししたいわけではないです、念のため）

**Comment by ponapalt** [comment]
http://home.384.jp/evidence/cgi-bin/archives/62.html
🤔

**Comment by nikolat** [comment]
これの後でTOAUTOEX作ったんでしたっけね。懐かしいです。
```
		if SHIORI3FW.AUTO_DATA_CONVERT {
			if ISINTSTR(_value) {
				var.req.value ,= TOINT(_value)
			}
			elseif ISREALSTR(_value) {
				var.req.value ,= TOREAL(_value)
			}
			else {
				var.req.value ,= REPLACE(_value, C_BYTE1, ",")	// バイト値1はカンマ化してしまう
			}
		}
		else {
			var.req.value ,= TOAUTOEX(_value)
		}

```
else以降の処理を推奨したいというか…。
バイト値1をカンマ化するのって色々不味いことが起こりそうじゃないです？

**Comment by ponapalt** [comment]
よし0にしよう！

**Comment by ponapalt** [comment]
せっかくだから TOAUTO の第2パラメータ新設して内部高速版TOAUTOEXにするのはどうかなと。

**Comment by nikolat** [comment]
いいっすね！
